name = "fotaasweb"
bin = "bin/fotaasweb"
vcs = "none"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = false
with_docker = true
with_grifts = true
as_web = true
as_api = false
