# FOTAAS docker-compose.yml

version: '3.1'

services:

  fotaasctl:
    container_name: fotaasctl
    image: us.gcr.io/kubedemo-233218/fotaas/fotaasctl
    build: ../cmd/fotaasctl
    links:
      - telemetry
      - analysis
      - simulation

  telemetry:
    container_name: telemetry
    image: us.gcr.io/kubedemo-233218/fotaas/telemetry
    build: ../cmd/telemetry
    expose:
      - 9411
      - 50051
    ports:
      - "50051:50051"

  analysis:
    container_name: analysis
    image: us.gcr.io/kubedemo-233218/fotaas/analysis
    build: ../cmd/analysis
    expose:
      - 9411
      - 50052
    ports:
      - "50052:50052"

  simulation:
    container_name: simulation
    image: us.gcr.io/kubedemo-233218/fotaas/simulation
    build: ../cmd/simulation
    expose:
      - 9411
      - 50053
    ports:
      - "50053:50053"

