# FOTAAS docker-compose-web.yml
# Used to create the FOTAAS fotaasweb docker image

version: '3.1'

services:

  fotaasweb:
    container_name: fotaasweb
    image: us.gcr.io/acoustic-skein-273916/fotaas/fotaasweb
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/web/fotaasweb/Dockerfile
    ports:
      - "8080:8080"
