# FOTAAS docker-compose-gke.yml
# Used to create the FOTAAS docker images which will be deployed to Google GKE

version: '3.1'

services:

  fotaasctl:
    container_name: fotaasctl
    image: us.gcr.io/acoustic-skein-273916/fotaas/fotaasctl
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/cmd/fotaasctl/Dockerfile
    links:
      - telemetry
      - analysis
      - simulation

  telemetry:
    container_name: telemetry
    image: us.gcr.io/acoustic-skein-273916/fotaas/telemetry
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/cmd/telemetry/Dockerfile    
    expose:
      - 9411
      - 50051
    ports:
      - "50051:50051"

  analysis:
    container_name: analysis
    image: us.gcr.io/acoustic-skein-273916/fotaas/analysis
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/cmd/analysis/Dockerfile    
    expose:
      - 9411
      - 50052
    ports:
      - "50052:50052"

  simulation:
    container_name: simulation
    image: us.gcr.io/acoustic-skein-273916/fotaas/simulation
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/cmd/simulation/Dockerfile
    expose:
      - 9411
      - 50053
    ports:
      - "50053:50053"

  status:
    container_name: status
    image: us.gcr.io/acoustic-skein-273916/fotaas/status
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/cmd/status/Dockerfile
    expose:
      - 9411
      - 50054
    ports:
      - "50054:50054"

  fotaasweb:
    container_name: fotaasweb
    image: us.gcr.io/acoustic-skein-273916/fotaas/fotaasweb
    build:
      context: ../
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/web/fotaasweb/Dockerfile
    ports:
      - "8080:8080"
               
