# FOTAAS docker-compose-web.yml
# Used to create the FOTAAS fotaasweb docker image

version: '3.1'

services:

  fotaasweb:
    container_name: fotaasweb
    image: us.gcr.io/kubedemo-233218/fotaas/fotaasweb
    build:
      context: .
      dockerfile: /Users/barry/go/src/github.com/bburch01/FOTAAS/web/fotaasweb/Dockerfile
