apiVersion: apps/v1
kind: Deployment
metadata:
  name: fotaas
  labels:
    app: fotaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fotaas
  template:
    metadata:
      labels:
        app: fotaas
    spec:
      containers:
      #START telemetry service container
      - name: telemetry
        image: localhost:5000/fotaas/telemetry
        ports:
        - containerPort: 50051
        env:
         - name: DB_HOST
           value: 127.0.0.1:3306
         - name: DB_USER
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: username
         - name: DB_PASSWORD
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: password
      #END telemetry service container
      #START analysis service container
      - name: analysis
        image: localhost:5000/fotaas/analysis
        ports:
        - containerPort: 50052
        env:
         - name: DB_HOST
           value: 127.0.0.1:3306
         - name: DB_USER
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: username
         - name: DB_PASSWORD
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: password 
      #END analysis service container
      #START simulation service container
      - name: simulation
        image: localhost:5000/fotaas/simulation
        ports:
        - containerPort: 50053
        env:
         - name: DB_HOST
           value: 127.0.0.1:3306
         - name: DB_USER
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: username
         - name: DB_PASSWORD
           valueFrom:
            secretKeyRef:
             name: cloudsql-db-credentials
             key: password
      #END telemetry service container
      #START fotaasctl container
      - name: fotaasctl
        image: localhost:5000/fotaas/fotaasctl
      #END fotaasctl container
      #START zipkin container
      - name: zipkin
        image: docker.io/openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
      #END zipkin container
      #Start cloudsql-proxy container
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy","-instances=kubedemo-233218:us-central1:kubedemodb=tcp:3306","-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
         runAsUser: 2  # non-root user
         allowPrivilegeEscalation: false
        volumeMounts:
         - name: cloudsql-instance-credentials
           mountPath: /secrets/cloudsql
           readOnly: true
      #END cloudsql-proxy container
      volumes:
       - name: cloudsql-instance-credentials
         secret:
          secretName: cloudsql-instance-credentials
