CREATE TABLE IF NOT EXISTS `simulation` 
(
  `id` VARCHAR(36) CHARACTER SET UTF8MB4 NOT NULL,
  `duration_in_minutes` INTEGER NOT NULL,
  `sample_rate` ENUM('SR_1_MS', 'SR_10_MS', 'SR_100_MS', 'SR_1000_MS') NOT NULL,  
  `grand_prix` ENUM('UNITED_STATES', 'AZERBAIJAN', 'SPANISH', 'GERMAN', 'HUNGARIAN',
        'BRAZILIAN', 'SINGAPORE', 'AUSTRALIAN', 'MEXICAN', 'MONACO',
        'CANADIAN', 'ITALIAN', 'FRENCH', 'BAHRAIN', 'CHINESE',
        'BRITISH', 'RUSSIAN', 'BELGIAN', 'AUSTRIAN', 'JAPANESE', 'ABU_DHABI') NOT NULL,
  `track` ENUM('AUSTIN', 'BAKU', 'CATALUNYA_BARCELONA', 'HOCKENHEIM', 'HUNGARORING',
        'INTERLAGOS_SAU_PAULO', 'MARINA_BAY', 'MELBOURNE', 'MEXICO_CITY', 'MONTE_CARLO',
        'MONTREAL', 'MONZA', 'PAUL_RICARD_LE_CASTELLET', 'SAKHIR', 'SHANGHAI',
        'SILVERSTONE', 'SOCHI', 'SPA_FRANCORCHAMPS', 'SPIELBERG_RED_BULL_RING', 'SUZUKA', 'YAS_MARINA') NOT NULL,
  `state` ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED_TO_START', 'FAILED') NOT NULL,  
  `start_timestamp` TIMESTAMP NULL,
  `end_timestamp` TIMESTAMP NULL,
  `percent_complete` FLOAT NOT NULL,
  `final_status_code` VARCHAR(36) CHARACTER SET UTF8MB4 NULL,
  `final_status_message` VARCHAR(255) CHARACTER SET UTF8MB4 NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;