// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FOTAAS.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Track int32

const (
	Track_AUSTIN                   Track = 0
	Track_BAKU                     Track = 1
	Track_CATALUNYA_BARCELONA      Track = 2
	Track_HOCKENHEIM               Track = 3
	Track_HUNGARORING              Track = 4
	Track_INTERLAGOS_SAU_PAULO     Track = 5
	Track_MARINA_BAY               Track = 6
	Track_MELBOURNE                Track = 7
	Track_MEXICO_CITY              Track = 8
	Track_MONTE_CARLO              Track = 9
	Track_MONTREAL                 Track = 10
	Track_MONZA                    Track = 11
	Track_PAUL_RICARD_LE_CASTELLET Track = 12
	Track_SAKHIR                   Track = 13
	Track_SHANGHAI                 Track = 14
	Track_SILVERSTONE              Track = 15
	Track_SOCHI                    Track = 16
	Track_SPA_FRANCORCHAMPS        Track = 17
	Track_SPIELBERG_RED_BULL_RING  Track = 18
	Track_SUZUKA                   Track = 19
	Track_YAS_MARINA               Track = 20
)

var Track_name = map[int32]string{
	0:  "AUSTIN",
	1:  "BAKU",
	2:  "CATALUNYA_BARCELONA",
	3:  "HOCKENHEIM",
	4:  "HUNGARORING",
	5:  "INTERLAGOS_SAU_PAULO",
	6:  "MARINA_BAY",
	7:  "MELBOURNE",
	8:  "MEXICO_CITY",
	9:  "MONTE_CARLO",
	10: "MONTREAL",
	11: "MONZA",
	12: "PAUL_RICARD_LE_CASTELLET",
	13: "SAKHIR",
	14: "SHANGHAI",
	15: "SILVERSTONE",
	16: "SOCHI",
	17: "SPA_FRANCORCHAMPS",
	18: "SPIELBERG_RED_BULL_RING",
	19: "SUZUKA",
	20: "YAS_MARINA",
}
var Track_value = map[string]int32{
	"AUSTIN":                   0,
	"BAKU":                     1,
	"CATALUNYA_BARCELONA":      2,
	"HOCKENHEIM":               3,
	"HUNGARORING":              4,
	"INTERLAGOS_SAU_PAULO":     5,
	"MARINA_BAY":               6,
	"MELBOURNE":                7,
	"MEXICO_CITY":              8,
	"MONTE_CARLO":              9,
	"MONTREAL":                 10,
	"MONZA":                    11,
	"PAUL_RICARD_LE_CASTELLET": 12,
	"SAKHIR":                   13,
	"SHANGHAI":                 14,
	"SILVERSTONE":              15,
	"SOCHI":                    16,
	"SPA_FRANCORCHAMPS":        17,
	"SPIELBERG_RED_BULL_RING":  18,
	"SUZUKA":                   19,
	"YAS_MARINA":               20,
}

func (x Track) String() string {
	return proto.EnumName(Track_name, int32(x))
}
func (Track) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{0}
}

type GrandPrix int32

const (
	GrandPrix_UNITED_STATES GrandPrix = 0
	GrandPrix_AZERBAIJAN    GrandPrix = 1
	GrandPrix_SPANISH       GrandPrix = 2
	GrandPrix_GERMAN        GrandPrix = 3
	GrandPrix_HUNGARIAN     GrandPrix = 4
	GrandPrix_BRAZILIAN     GrandPrix = 5
	GrandPrix_SINGAPORE     GrandPrix = 6
	GrandPrix_AUSTRALIAN    GrandPrix = 7
	GrandPrix_MEXICAN       GrandPrix = 8
	GrandPrix_MONACO        GrandPrix = 9
	GrandPrix_CANADIAN      GrandPrix = 10
	GrandPrix_ITALIAN       GrandPrix = 11
	GrandPrix_FRENCH        GrandPrix = 12
	GrandPrix_BAHRAIN       GrandPrix = 13
	GrandPrix_CHINESE       GrandPrix = 14
	GrandPrix_BRITISH       GrandPrix = 15
	GrandPrix_RUSSIAN       GrandPrix = 16
	GrandPrix_BELGIAN       GrandPrix = 17
	GrandPrix_AUSTRIAN      GrandPrix = 18
	GrandPrix_JAPANESE      GrandPrix = 19
	GrandPrix_ABU_DHABI     GrandPrix = 20
)

var GrandPrix_name = map[int32]string{
	0:  "UNITED_STATES",
	1:  "AZERBAIJAN",
	2:  "SPANISH",
	3:  "GERMAN",
	4:  "HUNGARIAN",
	5:  "BRAZILIAN",
	6:  "SINGAPORE",
	7:  "AUSTRALIAN",
	8:  "MEXICAN",
	9:  "MONACO",
	10: "CANADIAN",
	11: "ITALIAN",
	12: "FRENCH",
	13: "BAHRAIN",
	14: "CHINESE",
	15: "BRITISH",
	16: "RUSSIAN",
	17: "BELGIAN",
	18: "AUSTRIAN",
	19: "JAPANESE",
	20: "ABU_DHABI",
}
var GrandPrix_value = map[string]int32{
	"UNITED_STATES": 0,
	"AZERBAIJAN":    1,
	"SPANISH":       2,
	"GERMAN":        3,
	"HUNGARIAN":     4,
	"BRAZILIAN":     5,
	"SINGAPORE":     6,
	"AUSTRALIAN":    7,
	"MEXICAN":       8,
	"MONACO":        9,
	"CANADIAN":      10,
	"ITALIAN":       11,
	"FRENCH":        12,
	"BAHRAIN":       13,
	"CHINESE":       14,
	"BRITISH":       15,
	"RUSSIAN":       16,
	"BELGIAN":       17,
	"AUSTRIAN":      18,
	"JAPANESE":      19,
	"ABU_DHABI":     20,
}

func (x GrandPrix) String() string {
	return proto.EnumName(GrandPrix_name, int32(x))
}
func (GrandPrix) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{1}
}

type Constructor int32

const (
	Constructor_ALPHA_ROMEO        Constructor = 0
	Constructor_FERRARI            Constructor = 1
	Constructor_HAAS               Constructor = 2
	Constructor_MCLAREN            Constructor = 3
	Constructor_MERCEDES           Constructor = 4
	Constructor_RACING_POINT       Constructor = 5
	Constructor_RED_BULL_RACING    Constructor = 6
	Constructor_SCUDERIA_TORO_ROSO Constructor = 7
	Constructor_WILLIAMS           Constructor = 8
)

var Constructor_name = map[int32]string{
	0: "ALPHA_ROMEO",
	1: "FERRARI",
	2: "HAAS",
	3: "MCLAREN",
	4: "MERCEDES",
	5: "RACING_POINT",
	6: "RED_BULL_RACING",
	7: "SCUDERIA_TORO_ROSO",
	8: "WILLIAMS",
}
var Constructor_value = map[string]int32{
	"ALPHA_ROMEO":        0,
	"FERRARI":            1,
	"HAAS":               2,
	"MCLAREN":            3,
	"MERCEDES":           4,
	"RACING_POINT":       5,
	"RED_BULL_RACING":    6,
	"SCUDERIA_TORO_ROSO": 7,
	"WILLIAMS":           8,
}

func (x Constructor) String() string {
	return proto.EnumName(Constructor_name, int32(x))
}
func (Constructor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{2}
}

type TelemetryDatumUnit int32

const (
	TelemetryDatumUnit_G              TelemetryDatumUnit = 0
	TelemetryDatumUnit_KG_PER_HOUR    TelemetryDatumUnit = 1
	TelemetryDatumUnit_DEGREE_CELCIUS TelemetryDatumUnit = 2
	TelemetryDatumUnit_MJ             TelemetryDatumUnit = 3
	TelemetryDatumUnit_JPS            TelemetryDatumUnit = 4
	TelemetryDatumUnit_RPM            TelemetryDatumUnit = 5
	TelemetryDatumUnit_BAR            TelemetryDatumUnit = 6
	TelemetryDatumUnit_KG             TelemetryDatumUnit = 7
	TelemetryDatumUnit_KPH            TelemetryDatumUnit = 8
	TelemetryDatumUnit_METER          TelemetryDatumUnit = 9
	TelemetryDatumUnit_RADIAN         TelemetryDatumUnit = 10
	TelemetryDatumUnit_KPA            TelemetryDatumUnit = 11
)

var TelemetryDatumUnit_name = map[int32]string{
	0:  "G",
	1:  "KG_PER_HOUR",
	2:  "DEGREE_CELCIUS",
	3:  "MJ",
	4:  "JPS",
	5:  "RPM",
	6:  "BAR",
	7:  "KG",
	8:  "KPH",
	9:  "METER",
	10: "RADIAN",
	11: "KPA",
}
var TelemetryDatumUnit_value = map[string]int32{
	"G":              0,
	"KG_PER_HOUR":    1,
	"DEGREE_CELCIUS": 2,
	"MJ":             3,
	"JPS":            4,
	"RPM":            5,
	"BAR":            6,
	"KG":             7,
	"KPH":            8,
	"METER":          9,
	"RADIAN":         10,
	"KPA":            11,
}

func (x TelemetryDatumUnit) String() string {
	return proto.EnumName(TelemetryDatumUnit_name, int32(x))
}
func (TelemetryDatumUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{3}
}

type TelemetryDatumDescription int32

const (
	TelemetryDatumDescription_G_FORCE              TelemetryDatumDescription = 0
	TelemetryDatumDescription_G_FORCE_DIRECTION    TelemetryDatumDescription = 1
	TelemetryDatumDescription_FUEL_CONSUMED        TelemetryDatumDescription = 2
	TelemetryDatumDescription_FUEL_FLOW            TelemetryDatumDescription = 3
	TelemetryDatumDescription_ENGINE_COOLANT_TEMP  TelemetryDatumDescription = 4
	TelemetryDatumDescription_ENGINE_OIL_PRESSURE  TelemetryDatumDescription = 5
	TelemetryDatumDescription_ENGINE_OIL_TEMP      TelemetryDatumDescription = 6
	TelemetryDatumDescription_ENGINE_RPM           TelemetryDatumDescription = 7
	TelemetryDatumDescription_BRAKE_TEMP_FR        TelemetryDatumDescription = 8
	TelemetryDatumDescription_BRAKE_TEMP_FL        TelemetryDatumDescription = 9
	TelemetryDatumDescription_BRAKE_TEMP_RR        TelemetryDatumDescription = 10
	TelemetryDatumDescription_BRAKE_TEMP_RL        TelemetryDatumDescription = 11
	TelemetryDatumDescription_ENERGY_STORAGE_LEVEL TelemetryDatumDescription = 12
	TelemetryDatumDescription_ENERGY_STORAGE_TEMP  TelemetryDatumDescription = 13
	TelemetryDatumDescription_MGUK_OUTPUT          TelemetryDatumDescription = 14
	TelemetryDatumDescription_MGUH_OUTPUT          TelemetryDatumDescription = 15
	TelemetryDatumDescription_SPEED                TelemetryDatumDescription = 16
	TelemetryDatumDescription_TIRE_PRESSURE_FR     TelemetryDatumDescription = 17
	TelemetryDatumDescription_TIRE_PRESSURE_FL     TelemetryDatumDescription = 18
	TelemetryDatumDescription_TIRE_PRESSURE_RR     TelemetryDatumDescription = 19
	TelemetryDatumDescription_TIRE_PRESSURE_RL     TelemetryDatumDescription = 20
	TelemetryDatumDescription_TIRE_TEMP_FR         TelemetryDatumDescription = 21
	TelemetryDatumDescription_TIRE_TEMP_FL         TelemetryDatumDescription = 22
	TelemetryDatumDescription_TIRE_TEMP_RR         TelemetryDatumDescription = 23
	TelemetryDatumDescription_TIRE_TEMP_RL         TelemetryDatumDescription = 24
)

var TelemetryDatumDescription_name = map[int32]string{
	0:  "G_FORCE",
	1:  "G_FORCE_DIRECTION",
	2:  "FUEL_CONSUMED",
	3:  "FUEL_FLOW",
	4:  "ENGINE_COOLANT_TEMP",
	5:  "ENGINE_OIL_PRESSURE",
	6:  "ENGINE_OIL_TEMP",
	7:  "ENGINE_RPM",
	8:  "BRAKE_TEMP_FR",
	9:  "BRAKE_TEMP_FL",
	10: "BRAKE_TEMP_RR",
	11: "BRAKE_TEMP_RL",
	12: "ENERGY_STORAGE_LEVEL",
	13: "ENERGY_STORAGE_TEMP",
	14: "MGUK_OUTPUT",
	15: "MGUH_OUTPUT",
	16: "SPEED",
	17: "TIRE_PRESSURE_FR",
	18: "TIRE_PRESSURE_FL",
	19: "TIRE_PRESSURE_RR",
	20: "TIRE_PRESSURE_RL",
	21: "TIRE_TEMP_FR",
	22: "TIRE_TEMP_FL",
	23: "TIRE_TEMP_RR",
	24: "TIRE_TEMP_RL",
}
var TelemetryDatumDescription_value = map[string]int32{
	"G_FORCE":              0,
	"G_FORCE_DIRECTION":    1,
	"FUEL_CONSUMED":        2,
	"FUEL_FLOW":            3,
	"ENGINE_COOLANT_TEMP":  4,
	"ENGINE_OIL_PRESSURE":  5,
	"ENGINE_OIL_TEMP":      6,
	"ENGINE_RPM":           7,
	"BRAKE_TEMP_FR":        8,
	"BRAKE_TEMP_FL":        9,
	"BRAKE_TEMP_RR":        10,
	"BRAKE_TEMP_RL":        11,
	"ENERGY_STORAGE_LEVEL": 12,
	"ENERGY_STORAGE_TEMP":  13,
	"MGUK_OUTPUT":          14,
	"MGUH_OUTPUT":          15,
	"SPEED":                16,
	"TIRE_PRESSURE_FR":     17,
	"TIRE_PRESSURE_FL":     18,
	"TIRE_PRESSURE_RR":     19,
	"TIRE_PRESSURE_RL":     20,
	"TIRE_TEMP_FR":         21,
	"TIRE_TEMP_FL":         22,
	"TIRE_TEMP_RR":         23,
	"TIRE_TEMP_RL":         24,
}

func (x TelemetryDatumDescription) String() string {
	return proto.EnumName(TelemetryDatumDescription_name, int32(x))
}
func (TelemetryDatumDescription) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{4}
}

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var StatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{5}
}

type SimulationRateMultiplier int32

const (
	SimulationRateMultiplier_X1  SimulationRateMultiplier = 0
	SimulationRateMultiplier_X2  SimulationRateMultiplier = 1
	SimulationRateMultiplier_X4  SimulationRateMultiplier = 2
	SimulationRateMultiplier_X8  SimulationRateMultiplier = 3
	SimulationRateMultiplier_X10 SimulationRateMultiplier = 4
	SimulationRateMultiplier_X20 SimulationRateMultiplier = 5
)

var SimulationRateMultiplier_name = map[int32]string{
	0: "X1",
	1: "X2",
	2: "X4",
	3: "X8",
	4: "X10",
	5: "X20",
}
var SimulationRateMultiplier_value = map[string]int32{
	"X1":  0,
	"X2":  1,
	"X4":  2,
	"X8":  3,
	"X10": 4,
	"X20": 5,
}

func (x SimulationRateMultiplier) String() string {
	return proto.EnumName(SimulationRateMultiplier_name, int32(x))
}
func (SimulationRateMultiplier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{6}
}

type SampleRate int32

const (
	SampleRate_SR_1_MS    SampleRate = 0
	SampleRate_SR_10_MS   SampleRate = 1
	SampleRate_SR_100_MS  SampleRate = 2
	SampleRate_SR_1000_MS SampleRate = 3
)

var SampleRate_name = map[int32]string{
	0: "SR_1_MS",
	1: "SR_10_MS",
	2: "SR_100_MS",
	3: "SR_1000_MS",
}
var SampleRate_value = map[string]int32{
	"SR_1_MS":    0,
	"SR_10_MS":   1,
	"SR_100_MS":  2,
	"SR_1000_MS": 3,
}

func (x SampleRate) String() string {
	return proto.EnumName(SampleRate_name, int32(x))
}
func (SampleRate) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{7}
}

type ServerStatus struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=proto.StatusCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{0}
}
func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (dst *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(dst, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_OK
}

func (m *ServerStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{1}
}
func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(dst, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	ServerStatus         *ServerStatus `protobuf:"bytes,1,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{2}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(dst, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetServerStatus() *ServerStatus {
	if m != nil {
		return m.ServerStatus
	}
	return nil
}

type TelemetryDatum struct {
	Uuid                             string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Description                      TelemetryDatumDescription `protobuf:"varint,2,opt,name=description,proto3,enum=proto.TelemetryDatumDescription" json:"description,omitempty"`
	Unit                             TelemetryDatumUnit        `protobuf:"varint,3,opt,name=unit,proto3,enum=proto.TelemetryDatumUnit" json:"unit,omitempty"`
	Timestamp                        *timestamp.Timestamp      `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Latitude                         float64                   `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude                        float64                   `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Elevation                        float64                   `protobuf:"fixed64,7,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Value                            float64                   `protobuf:"fixed64,8,opt,name=value,proto3" json:"value,omitempty"`
	HighAlarm                        bool                      `protobuf:"varint,9,opt,name=high_alarm,json=highAlarm,proto3" json:"high_alarm,omitempty"`
	LowAlarm                         bool                      `protobuf:"varint,10,opt,name=low_alarm,json=lowAlarm,proto3" json:"low_alarm,omitempty"`
	Simulated                        bool                      `protobuf:"varint,11,opt,name=simulated,proto3" json:"simulated,omitempty"`
	SimulationUuid                   string                    `protobuf:"bytes,12,opt,name=simulation_uuid,json=simulationUuid,proto3" json:"simulation_uuid,omitempty"`
	SimulationTransmitSequenceNumber int32                     `protobuf:"varint,13,opt,name=simulation_transmit_sequence_number,json=simulationTransmitSequenceNumber,proto3" json:"simulation_transmit_sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                  `json:"-"`
	XXX_unrecognized                 []byte                    `json:"-"`
	XXX_sizecache                    int32                     `json:"-"`
}

func (m *TelemetryDatum) Reset()         { *m = TelemetryDatum{} }
func (m *TelemetryDatum) String() string { return proto.CompactTextString(m) }
func (*TelemetryDatum) ProtoMessage()    {}
func (*TelemetryDatum) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{3}
}
func (m *TelemetryDatum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryDatum.Unmarshal(m, b)
}
func (m *TelemetryDatum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryDatum.Marshal(b, m, deterministic)
}
func (dst *TelemetryDatum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryDatum.Merge(dst, src)
}
func (m *TelemetryDatum) XXX_Size() int {
	return xxx_messageInfo_TelemetryDatum.Size(m)
}
func (m *TelemetryDatum) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryDatum.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryDatum proto.InternalMessageInfo

func (m *TelemetryDatum) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TelemetryDatum) GetDescription() TelemetryDatumDescription {
	if m != nil {
		return m.Description
	}
	return TelemetryDatumDescription_G_FORCE
}

func (m *TelemetryDatum) GetUnit() TelemetryDatumUnit {
	if m != nil {
		return m.Unit
	}
	return TelemetryDatumUnit_G
}

func (m *TelemetryDatum) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TelemetryDatum) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *TelemetryDatum) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *TelemetryDatum) GetElevation() float64 {
	if m != nil {
		return m.Elevation
	}
	return 0
}

func (m *TelemetryDatum) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TelemetryDatum) GetHighAlarm() bool {
	if m != nil {
		return m.HighAlarm
	}
	return false
}

func (m *TelemetryDatum) GetLowAlarm() bool {
	if m != nil {
		return m.LowAlarm
	}
	return false
}

func (m *TelemetryDatum) GetSimulated() bool {
	if m != nil {
		return m.Simulated
	}
	return false
}

func (m *TelemetryDatum) GetSimulationUuid() string {
	if m != nil {
		return m.SimulationUuid
	}
	return ""
}

func (m *TelemetryDatum) GetSimulationTransmitSequenceNumber() int32 {
	if m != nil {
		return m.SimulationTransmitSequenceNumber
	}
	return 0
}

type TelemetryData struct {
	GrandPrix            GrandPrix                  `protobuf:"varint,1,opt,name=grand_prix,json=grandPrix,proto3,enum=proto.GrandPrix" json:"grand_prix,omitempty"`
	Track                Track                      `protobuf:"varint,2,opt,name=track,proto3,enum=proto.Track" json:"track,omitempty"`
	Constructor          Constructor                `protobuf:"varint,3,opt,name=constructor,proto3,enum=proto.Constructor" json:"constructor,omitempty"`
	CarNumber            int32                      `protobuf:"varint,4,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	TelemetryDatumMap    map[string]*TelemetryDatum `protobuf:"bytes,5,rep,name=telemetry_datum_map,json=telemetryDatumMap,proto3" json:"telemetry_datum_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TelemetryData) Reset()         { *m = TelemetryData{} }
func (m *TelemetryData) String() string { return proto.CompactTextString(m) }
func (*TelemetryData) ProtoMessage()    {}
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{4}
}
func (m *TelemetryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryData.Unmarshal(m, b)
}
func (m *TelemetryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryData.Marshal(b, m, deterministic)
}
func (dst *TelemetryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryData.Merge(dst, src)
}
func (m *TelemetryData) XXX_Size() int {
	return xxx_messageInfo_TelemetryData.Size(m)
}
func (m *TelemetryData) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryData.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryData proto.InternalMessageInfo

func (m *TelemetryData) GetGrandPrix() GrandPrix {
	if m != nil {
		return m.GrandPrix
	}
	return GrandPrix_UNITED_STATES
}

func (m *TelemetryData) GetTrack() Track {
	if m != nil {
		return m.Track
	}
	return Track_AUSTIN
}

func (m *TelemetryData) GetConstructor() Constructor {
	if m != nil {
		return m.Constructor
	}
	return Constructor_ALPHA_ROMEO
}

func (m *TelemetryData) GetCarNumber() int32 {
	if m != nil {
		return m.CarNumber
	}
	return 0
}

func (m *TelemetryData) GetTelemetryDatumMap() map[string]*TelemetryDatum {
	if m != nil {
		return m.TelemetryDatumMap
	}
	return nil
}

type TransmitTelemetryRequest struct {
	TelemetryData        *TelemetryData `protobuf:"bytes,1,opt,name=telemetry_data,json=telemetryData,proto3" json:"telemetry_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransmitTelemetryRequest) Reset()         { *m = TransmitTelemetryRequest{} }
func (m *TransmitTelemetryRequest) String() string { return proto.CompactTextString(m) }
func (*TransmitTelemetryRequest) ProtoMessage()    {}
func (*TransmitTelemetryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{5}
}
func (m *TransmitTelemetryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitTelemetryRequest.Unmarshal(m, b)
}
func (m *TransmitTelemetryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitTelemetryRequest.Marshal(b, m, deterministic)
}
func (dst *TransmitTelemetryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitTelemetryRequest.Merge(dst, src)
}
func (m *TransmitTelemetryRequest) XXX_Size() int {
	return xxx_messageInfo_TransmitTelemetryRequest.Size(m)
}
func (m *TransmitTelemetryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitTelemetryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitTelemetryRequest proto.InternalMessageInfo

func (m *TransmitTelemetryRequest) GetTelemetryData() *TelemetryData {
	if m != nil {
		return m.TelemetryData
	}
	return nil
}

type TransmitTelemetryResponse struct {
	ServerStatus         map[string]*ServerStatus `protobuf:"bytes,1,rep,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TransmitTelemetryResponse) Reset()         { *m = TransmitTelemetryResponse{} }
func (m *TransmitTelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*TransmitTelemetryResponse) ProtoMessage()    {}
func (*TransmitTelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{6}
}
func (m *TransmitTelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitTelemetryResponse.Unmarshal(m, b)
}
func (m *TransmitTelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitTelemetryResponse.Marshal(b, m, deterministic)
}
func (dst *TransmitTelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitTelemetryResponse.Merge(dst, src)
}
func (m *TransmitTelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_TransmitTelemetryResponse.Size(m)
}
func (m *TransmitTelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitTelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitTelemetryResponse proto.InternalMessageInfo

func (m *TransmitTelemetryResponse) GetServerStatus() map[string]*ServerStatus {
	if m != nil {
		return m.ServerStatus
	}
	return nil
}

type Simulation struct {
	Uuid                     string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DurationInMinutes        int32                    `protobuf:"varint,2,opt,name=duration_in_minutes,json=durationInMinutes,proto3" json:"duration_in_minutes,omitempty"`
	SampleRate               SampleRate               `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3,enum=proto.SampleRate" json:"sample_rate,omitempty"`
	SimulationRateMultiplier SimulationRateMultiplier `protobuf:"varint,4,opt,name=simulation_rate_multiplier,json=simulationRateMultiplier,proto3,enum=proto.SimulationRateMultiplier" json:"simulation_rate_multiplier,omitempty"`
	GrandPrix                GrandPrix                `protobuf:"varint,5,opt,name=grand_prix,json=grandPrix,proto3,enum=proto.GrandPrix" json:"grand_prix,omitempty"`
	Track                    Track                    `protobuf:"varint,6,opt,name=track,proto3,enum=proto.Track" json:"track,omitempty"`
	Constructor              Constructor              `protobuf:"varint,7,opt,name=constructor,proto3,enum=proto.Constructor" json:"constructor,omitempty"`
	CarNumber                int32                    `protobuf:"varint,8,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	ForceAlarm               bool                     `protobuf:"varint,9,opt,name=force_alarm,json=forceAlarm,proto3" json:"force_alarm,omitempty"`
	NoAlarms                 bool                     `protobuf:"varint,10,opt,name=no_alarms,json=noAlarms,proto3" json:"no_alarms,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                 `json:"-"`
	XXX_unrecognized         []byte                   `json:"-"`
	XXX_sizecache            int32                    `json:"-"`
}

func (m *Simulation) Reset()         { *m = Simulation{} }
func (m *Simulation) String() string { return proto.CompactTextString(m) }
func (*Simulation) ProtoMessage()    {}
func (*Simulation) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{7}
}
func (m *Simulation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Simulation.Unmarshal(m, b)
}
func (m *Simulation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Simulation.Marshal(b, m, deterministic)
}
func (dst *Simulation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Simulation.Merge(dst, src)
}
func (m *Simulation) XXX_Size() int {
	return xxx_messageInfo_Simulation.Size(m)
}
func (m *Simulation) XXX_DiscardUnknown() {
	xxx_messageInfo_Simulation.DiscardUnknown(m)
}

var xxx_messageInfo_Simulation proto.InternalMessageInfo

func (m *Simulation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Simulation) GetDurationInMinutes() int32 {
	if m != nil {
		return m.DurationInMinutes
	}
	return 0
}

func (m *Simulation) GetSampleRate() SampleRate {
	if m != nil {
		return m.SampleRate
	}
	return SampleRate_SR_1_MS
}

func (m *Simulation) GetSimulationRateMultiplier() SimulationRateMultiplier {
	if m != nil {
		return m.SimulationRateMultiplier
	}
	return SimulationRateMultiplier_X1
}

func (m *Simulation) GetGrandPrix() GrandPrix {
	if m != nil {
		return m.GrandPrix
	}
	return GrandPrix_UNITED_STATES
}

func (m *Simulation) GetTrack() Track {
	if m != nil {
		return m.Track
	}
	return Track_AUSTIN
}

func (m *Simulation) GetConstructor() Constructor {
	if m != nil {
		return m.Constructor
	}
	return Constructor_ALPHA_ROMEO
}

func (m *Simulation) GetCarNumber() int32 {
	if m != nil {
		return m.CarNumber
	}
	return 0
}

func (m *Simulation) GetForceAlarm() bool {
	if m != nil {
		return m.ForceAlarm
	}
	return false
}

func (m *Simulation) GetNoAlarms() bool {
	if m != nil {
		return m.NoAlarms
	}
	return false
}

type RunSimulationRequest struct {
	SimulationMap        map[string]*Simulation `protobuf:"bytes,1,rep,name=simulation_map,json=simulationMap,proto3" json:"simulation_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RunSimulationRequest) Reset()         { *m = RunSimulationRequest{} }
func (m *RunSimulationRequest) String() string { return proto.CompactTextString(m) }
func (*RunSimulationRequest) ProtoMessage()    {}
func (*RunSimulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{8}
}
func (m *RunSimulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSimulationRequest.Unmarshal(m, b)
}
func (m *RunSimulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSimulationRequest.Marshal(b, m, deterministic)
}
func (dst *RunSimulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSimulationRequest.Merge(dst, src)
}
func (m *RunSimulationRequest) XXX_Size() int {
	return xxx_messageInfo_RunSimulationRequest.Size(m)
}
func (m *RunSimulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSimulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunSimulationRequest proto.InternalMessageInfo

func (m *RunSimulationRequest) GetSimulationMap() map[string]*Simulation {
	if m != nil {
		return m.SimulationMap
	}
	return nil
}

type RunSimulationResponse struct {
	ServerStatus         map[string]*ServerStatus `protobuf:"bytes,1,rep,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RunSimulationResponse) Reset()         { *m = RunSimulationResponse{} }
func (m *RunSimulationResponse) String() string { return proto.CompactTextString(m) }
func (*RunSimulationResponse) ProtoMessage()    {}
func (*RunSimulationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{9}
}
func (m *RunSimulationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSimulationResponse.Unmarshal(m, b)
}
func (m *RunSimulationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSimulationResponse.Marshal(b, m, deterministic)
}
func (dst *RunSimulationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSimulationResponse.Merge(dst, src)
}
func (m *RunSimulationResponse) XXX_Size() int {
	return xxx_messageInfo_RunSimulationResponse.Size(m)
}
func (m *RunSimulationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSimulationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunSimulationResponse proto.InternalMessageInfo

func (m *RunSimulationResponse) GetServerStatus() map[string]*ServerStatus {
	if m != nil {
		return m.ServerStatus
	}
	return nil
}

type GetSimulationStatusRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSimulationStatusRequest) Reset()         { *m = GetSimulationStatusRequest{} }
func (m *GetSimulationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetSimulationStatusRequest) ProtoMessage()    {}
func (*GetSimulationStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{10}
}
func (m *GetSimulationStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSimulationStatusRequest.Unmarshal(m, b)
}
func (m *GetSimulationStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSimulationStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetSimulationStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSimulationStatusRequest.Merge(dst, src)
}
func (m *GetSimulationStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetSimulationStatusRequest.Size(m)
}
func (m *GetSimulationStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSimulationStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSimulationStatusRequest proto.InternalMessageInfo

func (m *GetSimulationStatusRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetSimulationStatusResponse struct {
	ServerStatus         *ServerStatus `protobuf:"bytes,1,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSimulationStatusResponse) Reset()         { *m = GetSimulationStatusResponse{} }
func (m *GetSimulationStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetSimulationStatusResponse) ProtoMessage()    {}
func (*GetSimulationStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FOTAAS_bbc6b678eddd40a5, []int{11}
}
func (m *GetSimulationStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSimulationStatusResponse.Unmarshal(m, b)
}
func (m *GetSimulationStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSimulationStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetSimulationStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSimulationStatusResponse.Merge(dst, src)
}
func (m *GetSimulationStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetSimulationStatusResponse.Size(m)
}
func (m *GetSimulationStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSimulationStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSimulationStatusResponse proto.InternalMessageInfo

func (m *GetSimulationStatusResponse) GetServerStatus() *ServerStatus {
	if m != nil {
		return m.ServerStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerStatus)(nil), "proto.ServerStatus")
	proto.RegisterType((*HealthCheckRequest)(nil), "proto.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "proto.HealthCheckResponse")
	proto.RegisterType((*TelemetryDatum)(nil), "proto.TelemetryDatum")
	proto.RegisterType((*TelemetryData)(nil), "proto.TelemetryData")
	proto.RegisterMapType((map[string]*TelemetryDatum)(nil), "proto.TelemetryData.TelemetryDatumMapEntry")
	proto.RegisterType((*TransmitTelemetryRequest)(nil), "proto.TransmitTelemetryRequest")
	proto.RegisterType((*TransmitTelemetryResponse)(nil), "proto.TransmitTelemetryResponse")
	proto.RegisterMapType((map[string]*ServerStatus)(nil), "proto.TransmitTelemetryResponse.ServerStatusEntry")
	proto.RegisterType((*Simulation)(nil), "proto.Simulation")
	proto.RegisterType((*RunSimulationRequest)(nil), "proto.RunSimulationRequest")
	proto.RegisterMapType((map[string]*Simulation)(nil), "proto.RunSimulationRequest.SimulationMapEntry")
	proto.RegisterType((*RunSimulationResponse)(nil), "proto.RunSimulationResponse")
	proto.RegisterMapType((map[string]*ServerStatus)(nil), "proto.RunSimulationResponse.ServerStatusEntry")
	proto.RegisterType((*GetSimulationStatusRequest)(nil), "proto.GetSimulationStatusRequest")
	proto.RegisterType((*GetSimulationStatusResponse)(nil), "proto.GetSimulationStatusResponse")
	proto.RegisterEnum("proto.Track", Track_name, Track_value)
	proto.RegisterEnum("proto.GrandPrix", GrandPrix_name, GrandPrix_value)
	proto.RegisterEnum("proto.Constructor", Constructor_name, Constructor_value)
	proto.RegisterEnum("proto.TelemetryDatumUnit", TelemetryDatumUnit_name, TelemetryDatumUnit_value)
	proto.RegisterEnum("proto.TelemetryDatumDescription", TelemetryDatumDescription_name, TelemetryDatumDescription_value)
	proto.RegisterEnum("proto.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("proto.SimulationRateMultiplier", SimulationRateMultiplier_name, SimulationRateMultiplier_value)
	proto.RegisterEnum("proto.SampleRate", SampleRate_name, SampleRate_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	TransmitTelemetry(ctx context.Context, in *TransmitTelemetryRequest, opts ...grpc.CallOption) (*TransmitTelemetryResponse, error)
}

type telemetryServiceClient struct {
	cc *grpc.ClientConn
}

func NewTelemetryServiceClient(cc *grpc.ClientConn) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.TelemetryService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) TransmitTelemetry(ctx context.Context, in *TransmitTelemetryRequest, opts ...grpc.CallOption) (*TransmitTelemetryResponse, error) {
	out := new(TransmitTelemetryResponse)
	err := c.cc.Invoke(ctx, "/proto.TelemetryService/TransmitTelemetry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
type TelemetryServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	TransmitTelemetry(context.Context, *TransmitTelemetryRequest) (*TransmitTelemetryResponse, error)
}

func RegisterTelemetryServiceServer(s *grpc.Server, srv TelemetryServiceServer) {
	s.RegisterService(&_TelemetryService_serviceDesc, srv)
}

func _TelemetryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TelemetryService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_TransmitTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).TransmitTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TelemetryService/TransmitTelemetry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).TransmitTelemetry(ctx, req.(*TransmitTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelemetryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TelemetryService_HealthCheck_Handler,
		},
		{
			MethodName: "TransmitTelemetry",
			Handler:    _TelemetryService_TransmitTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "FOTAAS.proto",
}

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type analysisServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnalysisServiceClient(cc *grpc.ClientConn) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.AnalysisService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
type AnalysisServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterAnalysisServiceServer(s *grpc.Server, srv AnalysisServiceServer) {
	s.RegisterService(&_AnalysisService_serviceDesc, srv)
}

func _AnalysisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AnalysisService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnalysisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AnalysisService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "FOTAAS.proto",
}

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulationServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	RunSimulation(ctx context.Context, in *RunSimulationRequest, opts ...grpc.CallOption) (*RunSimulationResponse, error)
	GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error)
}

type simulationServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimulationServiceClient(cc *grpc.ClientConn) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.SimulationService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) RunSimulation(ctx context.Context, in *RunSimulationRequest, opts ...grpc.CallOption) (*RunSimulationResponse, error) {
	out := new(RunSimulationResponse)
	err := c.cc.Invoke(ctx, "/proto.SimulationService/RunSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*GetSimulationStatusResponse, error) {
	out := new(GetSimulationStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.SimulationService/GetSimulationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
type SimulationServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	RunSimulation(context.Context, *RunSimulationRequest) (*RunSimulationResponse, error)
	GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*GetSimulationStatusResponse, error)
}

func RegisterSimulationServiceServer(s *grpc.Server, srv SimulationServiceServer) {
	s.RegisterService(&_SimulationService_serviceDesc, srv)
}

func _SimulationService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SimulationService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_RunSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).RunSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SimulationService/RunSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).RunSimulation(ctx, req.(*RunSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetSimulationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetSimulationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SimulationService/GetSimulationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetSimulationStatus(ctx, req.(*GetSimulationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimulationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _SimulationService_HealthCheck_Handler,
		},
		{
			MethodName: "RunSimulation",
			Handler:    _SimulationService_RunSimulation_Handler,
		},
		{
			MethodName: "GetSimulationStatus",
			Handler:    _SimulationService_GetSimulationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "FOTAAS.proto",
}

func init() { proto.RegisterFile("FOTAAS.proto", fileDescriptor_FOTAAS_bbc6b678eddd40a5) }

var fileDescriptor_FOTAAS_bbc6b678eddd40a5 = []byte{
	// 1980 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x16, 0xf8, 0x23, 0x92, 0x4d, 0x51, 0x1a, 0x8e, 0xe4, 0x35, 0x4d, 0x3b, 0x65, 0x85, 0xa9,
	0xd4, 0x2a, 0xda, 0x8a, 0x6c, 0x33, 0x7b, 0x70, 0x25, 0xa7, 0x21, 0x38, 0x02, 0x61, 0x81, 0x00,
	0xab, 0x01, 0xac, 0x25, 0x6f, 0x25, 0x53, 0x30, 0x85, 0x95, 0x59, 0xe6, 0x8f, 0x42, 0x80, 0xde,
	0xf5, 0x3d, 0x97, 0x1c, 0x53, 0x95, 0x6b, 0xde, 0x21, 0x87, 0x3c, 0xc1, 0x1e, 0x93, 0x87, 0xc9,
	0x21, 0x2f, 0x90, 0x9a, 0x01, 0xf8, 0x2b, 0xca, 0xf9, 0xdb, 0xaa, 0x9c, 0x80, 0xee, 0xaf, 0xa7,
	0xa7, 0xa7, 0xfb, 0xeb, 0xc6, 0x00, 0xf6, 0xce, 0x1d, 0x8f, 0x31, 0xf7, 0xec, 0x76, 0x3a, 0x89,
	0x27, 0x34, 0xaf, 0x1e, 0xf5, 0xa7, 0x37, 0x93, 0xc9, 0xcd, 0x30, 0x7c, 0xa6, 0xa4, 0xb7, 0xb3,
	0x6f, 0x9e, 0xc5, 0x83, 0x51, 0x18, 0xc5, 0xc1, 0xe8, 0x36, 0xb1, 0x6b, 0x38, 0xb0, 0xe7, 0x86,
	0xd3, 0x0f, 0xe1, 0xd4, 0x8d, 0x83, 0x78, 0x16, 0xd1, 0x9f, 0x42, 0xae, 0x3f, 0xb9, 0x0e, 0x6b,
	0xda, 0xb1, 0x76, 0xb2, 0xdf, 0xac, 0x26, 0x56, 0x67, 0x09, 0xa8, 0x4f, 0xae, 0x43, 0x54, 0x30,
	0xad, 0x41, 0x61, 0x14, 0x46, 0x51, 0x70, 0x13, 0xd6, 0x32, 0xc7, 0xda, 0x49, 0x09, 0xe7, 0x62,
	0xe3, 0x08, 0x68, 0x27, 0x0c, 0x86, 0xf1, 0x3b, 0xfd, 0x5d, 0xd8, 0x7f, 0x8f, 0xe1, 0x6f, 0x67,
	0x61, 0x14, 0x37, 0x1c, 0x38, 0x5c, 0xd3, 0x46, 0xb7, 0x93, 0x71, 0x14, 0xd2, 0x97, 0x50, 0x89,
	0xd4, 0xee, 0x22, 0x52, 0x3b, 0xa8, 0x6d, 0xcb, 0xcd, 0xc3, 0xf9, 0xb6, 0x2b, 0x91, 0xe1, 0x5e,
	0xb4, 0x22, 0x35, 0xfe, 0x90, 0x83, 0x7d, 0x2f, 0x1c, 0x86, 0xa3, 0x30, 0x9e, 0x7e, 0x6c, 0x07,
	0xf1, 0x6c, 0x44, 0x29, 0xe4, 0x66, 0xb3, 0xc1, 0xb5, 0xf2, 0x51, 0x42, 0xf5, 0x4e, 0x5b, 0x50,
	0xbe, 0x0e, 0xa3, 0xfe, 0x74, 0x70, 0x1b, 0x0f, 0x26, 0x63, 0x15, 0xeb, 0x7e, 0xf3, 0x38, 0x75,
	0xbf, 0xbe, 0xbe, 0xbd, 0xb4, 0xc3, 0xd5, 0x45, 0xf4, 0xe7, 0x90, 0x9b, 0x8d, 0x07, 0x71, 0x2d,
	0xab, 0x16, 0x3f, 0xda, 0xba, 0xd8, 0x1f, 0x0f, 0x62, 0x54, 0x66, 0xf4, 0x25, 0x94, 0x16, 0x49,
	0xae, 0xe5, 0xd4, 0x79, 0xea, 0x67, 0x49, 0x19, 0xce, 0xe6, 0x65, 0x38, 0xf3, 0xe6, 0x16, 0xb8,
	0x34, 0xa6, 0x75, 0x28, 0x0e, 0x83, 0x78, 0x10, 0xcf, 0xae, 0xc3, 0x5a, 0xfe, 0x58, 0x3b, 0xd1,
	0x70, 0x21, 0xd3, 0x27, 0x50, 0x1a, 0x4e, 0xc6, 0x37, 0x09, 0xb8, 0xab, 0xc0, 0xa5, 0x42, 0xa2,
	0xe1, 0x30, 0xfc, 0x10, 0xa8, 0x43, 0x16, 0x12, 0x74, 0xa1, 0xa0, 0x47, 0x90, 0xff, 0x10, 0x0c,
	0x67, 0x61, 0xad, 0xa8, 0x90, 0x44, 0xa0, 0x3f, 0x02, 0x78, 0x37, 0xb8, 0x79, 0x27, 0x82, 0x61,
	0x30, 0x1d, 0xd5, 0x4a, 0xc7, 0xda, 0x49, 0x11, 0x4b, 0x52, 0xc3, 0xa4, 0x82, 0x3e, 0x96, 0x1b,
	0x7e, 0x9b, 0xa2, 0xa0, 0xd0, 0xe2, 0x70, 0xf2, 0x6d, 0x02, 0x3e, 0x81, 0x52, 0x34, 0x18, 0xcd,
	0x86, 0x41, 0x1c, 0x5e, 0xd7, 0xca, 0xc9, 0xd2, 0x85, 0x82, 0x7e, 0x0e, 0x07, 0xa9, 0x30, 0x98,
	0x8c, 0x85, 0xaa, 0xc9, 0x9e, 0xaa, 0xc9, 0xfe, 0x52, 0xed, 0xcb, 0xea, 0x74, 0xe1, 0x27, 0x2b,
	0x86, 0xf1, 0x34, 0x18, 0x47, 0xa3, 0x41, 0x2c, 0x22, 0x49, 0x9a, 0x71, 0x3f, 0x14, 0xe3, 0xd9,
	0xe8, 0x6d, 0x38, 0xad, 0x55, 0x8e, 0xb5, 0x93, 0x3c, 0x1e, 0x2f, 0x4d, 0xbd, 0xd4, 0xd2, 0x4d,
	0x0d, 0x6d, 0x65, 0xd7, 0xf8, 0x47, 0x06, 0x2a, 0xab, 0x65, 0x09, 0xe8, 0x33, 0x80, 0x9b, 0x69,
	0x30, 0xbe, 0x16, 0xb7, 0xd3, 0xc1, 0x77, 0x29, 0xa7, 0x49, 0x5a, 0x40, 0x43, 0x02, 0xbd, 0xe9,
	0xe0, 0x3b, 0x2c, 0xdd, 0xcc, 0x5f, 0x69, 0x03, 0xf2, 0xf1, 0x34, 0xe8, 0xbf, 0x4f, 0x99, 0xb2,
	0x37, 0x2f, 0xb6, 0xd4, 0x61, 0x02, 0xd1, 0x2f, 0xa1, 0xdc, 0x9f, 0x8c, 0xa3, 0x78, 0x3a, 0xeb,
	0xc7, 0x93, 0x69, 0x4a, 0x0b, 0x9a, 0x5a, 0xea, 0x4b, 0x04, 0x57, 0xcd, 0x64, 0xba, 0xfb, 0xc1,
	0x74, 0x7e, 0xa4, 0x9c, 0x3a, 0x52, 0xa9, 0x1f, 0x4c, 0x93, 0xd8, 0xe9, 0xd7, 0x70, 0x18, 0xcf,
	0x43, 0x17, 0xd7, 0x92, 0x52, 0x62, 0x14, 0xdc, 0xd6, 0xf2, 0xc7, 0xd9, 0x93, 0x72, 0xf3, 0x8b,
	0x2d, 0x9c, 0x0b, 0x36, 0x18, 0xd8, 0x0d, 0x6e, 0xf9, 0x38, 0x9e, 0x7e, 0xc4, 0x6a, 0xbc, 0xa9,
	0xaf, 0x7f, 0x0d, 0x9f, 0x6d, 0x37, 0xa6, 0x04, 0xb2, 0xef, 0xc3, 0x8f, 0x69, 0xcb, 0xc8, 0x57,
	0xfa, 0xc5, 0x9c, 0x2c, 0x19, 0x45, 0xdd, 0x07, 0x5b, 0xe9, 0x9e, 0x72, 0xe8, 0x97, 0x99, 0x97,
	0x5a, 0xe3, 0x35, 0xd4, 0xe6, 0xf5, 0x58, 0x18, 0xa5, 0x6d, 0x4f, 0x7f, 0x05, 0xfb, 0x6b, 0xa7,
	0x0a, 0xd2, 0x06, 0x3f, 0xda, 0x76, 0x20, 0xac, 0xac, 0x46, 0x1e, 0x34, 0xfe, 0xaa, 0xc1, 0xa3,
	0x2d, 0x9e, 0xd3, 0xd1, 0xf1, 0xfa, 0xee, 0xe8, 0x90, 0xa9, 0x6a, 0x2e, 0x2b, 0xb6, 0x7d, 0xe1,
	0xda, 0x50, 0x49, 0x32, 0xb6, 0x36, 0x59, 0xea, 0x1e, 0x54, 0xef, 0x98, 0x6c, 0xc9, 0xd3, 0xcf,
	0xd6, 0xf3, 0xb4, 0x75, 0x64, 0xad, 0x64, 0xe9, 0x6f, 0x59, 0x00, 0x77, 0x41, 0xe0, 0xad, 0xb3,
	0xea, 0x0c, 0x0e, 0xaf, 0x67, 0xd3, 0xa4, 0x17, 0x06, 0x63, 0x31, 0x1a, 0x8c, 0x67, 0x71, 0x18,
	0x29, 0xff, 0x79, 0xac, 0xce, 0x21, 0x73, 0xdc, 0x4d, 0x00, 0xda, 0x84, 0x72, 0x14, 0x8c, 0x6e,
	0x87, 0xa1, 0x98, 0x06, 0x71, 0x98, 0xf2, 0x70, 0x31, 0xb1, 0x15, 0x82, 0x41, 0x1c, 0x22, 0x44,
	0x8b, 0x77, 0xfa, 0x6b, 0xa8, 0xaf, 0x74, 0x9c, 0x5c, 0x27, 0x46, 0xb3, 0x61, 0x3c, 0xb8, 0x1d,
	0x0e, 0x52, 0x56, 0xee, 0x37, 0x9f, 0xce, 0x5d, 0x2c, 0x0c, 0xe5, 0xd2, 0xee, 0xc2, 0x0c, 0x6b,
	0xd1, 0x3d, 0xc8, 0x46, 0xbf, 0xe5, 0xff, 0x83, 0x7e, 0xdb, 0xfd, 0xb7, 0xfb, 0xad, 0xf0, 0xdf,
	0xf4, 0x5b, 0x71, 0xb3, 0xdf, 0x9e, 0x42, 0xf9, 0x9b, 0xc9, 0xb4, 0x1f, 0xae, 0x8d, 0x3f, 0x50,
	0xaa, 0xc5, 0xfc, 0x1b, 0x4f, 0x12, 0x34, 0x9a, 0xcf, 0xbf, 0xf1, 0x44, 0x61, 0x51, 0xe3, 0x7b,
	0x0d, 0x8e, 0x70, 0x36, 0x5e, 0xc9, 0x50, 0x4a, 0x78, 0x1f, 0x56, 0x66, 0x9c, 0xea, 0xe0, 0x84,
	0x96, 0x67, 0x69, 0xb8, 0xdb, 0x16, 0xad, 0x24, 0x7a, 0xd1, 0xc4, 0x95, 0x68, 0x55, 0x57, 0x77,
	0x81, 0xde, 0x35, 0xda, 0x42, 0xca, 0xcf, 0xd7, 0x49, 0x59, 0xbd, 0x5b, 0xc9, 0x15, 0x4a, 0x7e,
	0xaf, 0xc1, 0x83, 0x8d, 0x78, 0xd2, 0xde, 0x72, 0xb7, 0xf7, 0xd6, 0x3d, 0x87, 0xf8, 0xbf, 0xf6,
	0xd5, 0x73, 0xa8, 0x1b, 0x61, 0xbc, 0x0c, 0x27, 0xb5, 0x48, 0xcb, 0xb1, 0xa5, 0xcd, 0x1a, 0xaf,
	0xe1, 0xf1, 0xd6, 0x15, 0xff, 0xeb, 0x95, 0xe4, 0xf4, 0xef, 0x19, 0xc8, 0x2b, 0xe2, 0x52, 0x80,
	0x5d, 0xe6, 0xbb, 0x9e, 0x69, 0x93, 0x1d, 0x5a, 0x84, 0x5c, 0x8b, 0x5d, 0xf8, 0x44, 0xa3, 0x0f,
	0xe1, 0x50, 0x67, 0x1e, 0xb3, 0x7c, 0xfb, 0x8a, 0x89, 0x16, 0x43, 0x9d, 0x5b, 0x8e, 0xcd, 0x48,
	0x86, 0xee, 0x03, 0x74, 0x1c, 0xfd, 0x82, 0xdb, 0x1d, 0x6e, 0x76, 0x49, 0x96, 0x1e, 0x40, 0xb9,
	0xe3, 0xdb, 0x06, 0x43, 0x07, 0x4d, 0xdb, 0x20, 0x39, 0x5a, 0x83, 0x23, 0xd3, 0xf6, 0x38, 0x5a,
	0xcc, 0x70, 0x5c, 0xe1, 0x32, 0x5f, 0xf4, 0x98, 0x6f, 0x39, 0x24, 0x2f, 0x97, 0x76, 0x19, 0x9a,
	0xb6, 0x74, 0x78, 0x45, 0x76, 0x69, 0x05, 0x4a, 0x5d, 0x6e, 0xb5, 0x1c, 0x1f, 0x6d, 0x4e, 0x0a,
	0xd2, 0x53, 0x97, 0x5f, 0x9a, 0xba, 0x23, 0x74, 0xd3, 0xbb, 0x22, 0x45, 0xa5, 0x70, 0x6c, 0x8f,
	0x0b, 0x9d, 0xa1, 0xe5, 0x90, 0x12, 0xdd, 0x83, 0xa2, 0x54, 0x20, 0x67, 0x16, 0x01, 0x5a, 0x82,
	0x7c, 0xd7, 0xb1, 0xdf, 0x30, 0x52, 0xa6, 0x4f, 0xa0, 0x26, 0x37, 0x11, 0x68, 0xea, 0x0c, 0xdb,
	0xc2, 0x92, 0x4b, 0x5c, 0x8f, 0x5b, 0x16, 0xf7, 0xc8, 0x9e, 0x3c, 0xa1, 0xcb, 0x2e, 0x3a, 0x26,
	0x92, 0x8a, 0x74, 0xe1, 0x76, 0x98, 0x6d, 0x74, 0x98, 0x49, 0xf6, 0xe5, 0x0e, 0xae, 0x69, 0x7d,
	0xc5, 0xd1, 0xf5, 0x1c, 0x9b, 0x93, 0x03, 0xe9, 0xd3, 0x75, 0xf4, 0x8e, 0x49, 0x08, 0x7d, 0x00,
	0x55, 0xb7, 0xc7, 0xc4, 0x39, 0x32, 0x5b, 0x77, 0x50, 0xef, 0xb0, 0x6e, 0xcf, 0x25, 0x55, 0xfa,
	0x18, 0x1e, 0xba, 0x3d, 0x93, 0x5b, 0x2d, 0x8e, 0x86, 0x40, 0xde, 0x16, 0x2d, 0xdf, 0x92, 0x1b,
	0xdb, 0x06, 0xa1, 0x6a, 0x27, 0xff, 0x8d, 0x7f, 0xc1, 0xc8, 0xa1, 0x3c, 0xed, 0x15, 0x73, 0x45,
	0x72, 0x62, 0x72, 0x74, 0xfa, 0xe7, 0x0c, 0x94, 0x16, 0x63, 0x85, 0x56, 0xa1, 0xe2, 0xdb, 0xa6,
	0xc7, 0xdb, 0xc2, 0xf5, 0x98, 0xc7, 0x5d, 0xb2, 0x23, 0x17, 0xb0, 0x37, 0x1c, 0x5b, 0xcc, 0x7c,
	0xc5, 0x6c, 0xa2, 0xd1, 0x32, 0x14, 0xdc, 0x1e, 0xb3, 0x4d, 0xb7, 0x43, 0x32, 0xd2, 0xb3, 0xc1,
	0xb1, 0xcb, 0x6c, 0x92, 0x95, 0x79, 0x4b, 0x52, 0x6e, 0x32, 0x9b, 0xe4, 0xa4, 0xd8, 0x42, 0xf6,
	0xc6, 0xb4, 0xa4, 0x98, 0x97, 0xa2, 0x6b, 0xda, 0x06, 0xeb, 0x39, 0xc8, 0xc9, 0xae, 0xf2, 0xea,
	0xbb, 0x1e, 0x32, 0x05, 0x17, 0xa4, 0x57, 0x95, 0x65, 0x66, 0x93, 0xa2, 0xf4, 0xda, 0x75, 0x6c,
	0xa6, 0xa7, 0xc9, 0xd5, 0x99, 0xcd, 0xda, 0xd2, 0x0c, 0xa4, 0x99, 0xe9, 0x25, 0x6b, 0xca, 0xd2,
	0xec, 0x1c, 0xb9, 0xad, 0x77, 0xc8, 0x9e, 0x04, 0x5a, 0xac, 0x83, 0xcc, 0xb4, 0x49, 0x45, 0x0a,
	0x7a, 0xc7, 0xb4, 0xb9, 0xcb, 0xc9, 0xbe, 0x42, 0xd0, 0xf4, 0x64, 0xbc, 0x07, 0x52, 0x40, 0xdf,
	0x75, 0xe5, 0x7a, 0xa2, 0x10, 0x6e, 0x19, 0x52, 0xa8, 0xca, 0x7d, 0x54, 0x40, 0x52, 0xa2, 0x52,
	0x7a, 0xc5, 0x7a, 0x4c, 0xb9, 0x38, 0x94, 0xb1, 0xb3, 0x96, 0x2f, 0xda, 0x1d, 0xd6, 0x32, 0xc9,
	0xd1, 0xe9, 0x9f, 0x34, 0x28, 0xaf, 0xcc, 0x4c, 0x59, 0x2e, 0x66, 0xf5, 0x3a, 0x4c, 0xa0, 0xd3,
	0xe5, 0x0e, 0xd9, 0x91, 0x8e, 0xcf, 0x39, 0x22, 0x43, 0x93, 0x68, 0x92, 0xbc, 0x1d, 0xc6, 0x5c,
	0x92, 0x51, 0x67, 0xd4, 0x2d, 0x86, 0x5c, 0x66, 0x4b, 0x92, 0x86, 0xa3, 0xce, 0xdb, 0xdc, 0x25,
	0x39, 0x4a, 0x60, 0x0f, 0x99, 0x6e, 0xda, 0x86, 0xe8, 0x39, 0xa6, 0xed, 0x91, 0x3c, 0x3d, 0x84,
	0x83, 0x65, 0x19, 0x15, 0x44, 0x76, 0xe9, 0x67, 0x40, 0x5d, 0xdd, 0x6f, 0x73, 0x34, 0x99, 0xf0,
	0x1c, 0x74, 0x04, 0x3a, 0xae, 0x43, 0x0a, 0xd2, 0xd9, 0x6b, 0xd3, 0xb2, 0x4c, 0xd6, 0x75, 0x49,
	0xf1, 0xf4, 0x8f, 0x1a, 0xd0, 0xbb, 0x57, 0x6b, 0x9a, 0x07, 0xcd, 0x20, 0x3b, 0x32, 0xda, 0x0b,
	0x43, 0xf4, 0x38, 0x8a, 0x8e, 0xe3, 0x23, 0xd1, 0x28, 0x85, 0xfd, 0x36, 0x37, 0x90, 0x73, 0xa1,
	0x73, 0x4b, 0x37, 0x7d, 0x19, 0xea, 0x2e, 0x64, 0xba, 0xaf, 0x48, 0x96, 0x16, 0x20, 0xfb, 0xaa,
	0x27, 0x03, 0x2c, 0x40, 0x16, 0x7b, 0x5d, 0x92, 0x97, 0x2f, 0x2d, 0x86, 0x64, 0x57, 0x9a, 0x5c,
	0x18, 0xa4, 0x20, 0x15, 0x17, 0xbd, 0x0e, 0x29, 0x2a, 0xe2, 0x73, 0x8f, 0x23, 0x29, 0xc9, 0xca,
	0xe0, 0xbc, 0x64, 0x0a, 0x67, 0xa4, 0x7c, 0xfa, 0xbb, 0x1c, 0x3c, 0xba, 0xf7, 0x77, 0x41, 0x26,
	0xc7, 0x10, 0xe7, 0x0e, 0xea, 0x9c, 0xec, 0x48, 0x92, 0xa7, 0x82, 0x68, 0x9b, 0xc8, 0x75, 0xcf,
	0x74, 0x24, 0xf5, 0xaa, 0x50, 0x39, 0xf7, 0xb9, 0x25, 0x74, 0xc7, 0x76, 0xfd, 0x2e, 0x6f, 0x93,
	0x8c, 0x2c, 0x8d, 0x52, 0x9d, 0x5b, 0xce, 0x6b, 0x92, 0x95, 0xf3, 0x81, 0xdb, 0x86, 0x69, 0x73,
	0xa1, 0x3b, 0x8e, 0xc5, 0x6c, 0x4f, 0x78, 0xbc, 0xdb, 0x23, 0xb9, 0x15, 0xc0, 0x31, 0x2d, 0xd1,
	0x43, 0xee, 0xba, 0x3e, 0xf2, 0x24, 0xcf, 0x2b, 0x80, 0xb2, 0x56, 0xec, 0x4c, 0x95, 0xf2, 0xd0,
	0x05, 0xb9, 0x71, 0x0b, 0xd9, 0x05, 0x57, 0xb8, 0x38, 0x47, 0x52, 0xdc, 0x54, 0x59, 0xa4, 0xb4,
	0xa1, 0x42, 0x24, 0xb0, 0xa9, 0xb2, 0x48, 0x59, 0x0e, 0x22, 0x6e, 0x73, 0x34, 0xae, 0x84, 0xeb,
	0x39, 0xc8, 0x0c, 0x2e, 0x2c, 0xfe, 0x15, 0xb7, 0xc8, 0x5e, 0x12, 0xe3, 0x1a, 0xa2, 0xc2, 0xa9,
	0xa8, 0x89, 0x63, 0xf8, 0x17, 0xc2, 0xf1, 0xbd, 0x9e, 0xef, 0x25, 0x03, 0xa2, 0x6b, 0xf8, 0x9d,
	0xb9, 0x22, 0x19, 0x10, 0x3d, 0xce, 0xdb, 0x84, 0xd0, 0x23, 0x20, 0x9e, 0x89, 0x7c, 0x71, 0x46,
	0x19, 0x6e, 0x75, 0x8b, 0xd6, 0x22, 0xf4, 0xae, 0x16, 0x91, 0x1c, 0x6e, 0xd1, 0x5a, 0xe4, 0x48,
	0x52, 0x54, 0x69, 0xe7, 0x29, 0x78, 0xb0, 0xa1, 0xb1, 0xc8, 0x67, 0xeb, 0x1a, 0x44, 0xf2, 0x70,
	0x43, 0x63, 0x91, 0xda, 0xe9, 0x53, 0x80, 0xe5, 0xaf, 0xb0, 0x64, 0x91, 0x73, 0x41, 0x76, 0xe4,
	0x01, 0x38, 0xa2, 0x83, 0x44, 0x3b, 0xb5, 0xa0, 0x76, 0xdf, 0xb5, 0x49, 0x9a, 0x5f, 0xbe, 0x20,
	0x3b, 0xea, 0xd9, 0x24, 0x9a, 0x7a, 0x7e, 0x99, 0xf0, 0xf5, 0xf2, 0x65, 0xc2, 0xd7, 0xcb, 0x17,
	0xcf, 0x13, 0xbe, 0x5e, 0x36, 0x9f, 0x93, 0xfc, 0xe9, 0x39, 0xc0, 0xf2, 0x1e, 0xa7, 0x86, 0x17,
	0x8a, 0x17, 0xa2, 0x2b, 0x27, 0x9b, 0x1c, 0xba, 0x28, 0x5e, 0x3c, 0x97, 0x92, 0xa6, 0x06, 0x94,
	0x94, 0x94, 0xa8, 0x3e, 0x28, 0x89, 0xa8, 0xe4, 0x6c, 0xf3, 0x2f, 0x1a, 0x90, 0x05, 0x7b, 0xe5,
	0x17, 0x6c, 0xd0, 0x0f, 0xe9, 0x39, 0x94, 0x57, 0x7e, 0xc9, 0xe9, 0xfc, 0xbf, 0xf6, 0xee, 0xcf,
	0x7b, 0xbd, 0xbe, 0x0d, 0x4a, 0x3e, 0x97, 0x8d, 0x1d, 0x7a, 0x09, 0xd5, 0x3b, 0x97, 0x6d, 0xfa,
	0xf4, 0xfe, 0x6b, 0x78, 0xe2, 0xf3, 0xf8, 0x5f, 0xdd, 0xd3, 0x1b, 0x3b, 0xcd, 0x2b, 0x38, 0x60,
	0xe3, 0x60, 0xf8, 0x31, 0x1a, 0x44, 0x3f, 0x70, 0xd0, 0xcd, 0xdf, 0x67, 0xa0, 0xba, 0x72, 0x05,
	0xf8, 0x81, 0x53, 0x62, 0x41, 0x65, 0xed, 0x8e, 0x44, 0x1f, 0x7f, 0xe2, 0xfa, 0x57, 0x7f, 0xf2,
	0xa9, 0x6b, 0x55, 0x63, 0x87, 0xfe, 0x06, 0x0e, 0xb7, 0x5c, 0x58, 0xe8, 0x8f, 0xe7, 0xf7, 0xea,
	0x7b, 0xaf, 0x3f, 0xf5, 0xc6, 0xa7, 0x4c, 0xe6, 0xfe, 0xdf, 0xee, 0x2a, 0xa3, 0x5f, 0xfc, 0x33,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0x87, 0xbe, 0x22, 0x41, 0x12, 0x00, 0x00,
}
